### ISSUE TITLE
Proposal: Switch to TypeScript

### ISSUE THREAD

**Issue by MrKomish** [morbyosef/NotThatNiceLookingDebugger#1]
CPP is not in fashion any more.
Move on.

A guide for rookies: https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html.

**Comment by morbyosef** [comment]
Your enlightenment will be taken and The next debugger I'll write will be in Typescript.
Thanks for telling us your opinion.

NotThatNiceLookingDebugger support team.
