### ISSUE TITLE
Proposal: Add graphql API

### ISSUE THREAD

**Issue by MrKomish** [morbyosef/NotThatNiceLookingDebugger#2]
A big chunk of this project extensive user base seems to use https://graphql.org/learn/ for their public APIs,
I think the community around this project would get tremendous benefit from integrating GraphQL in the next release. 

Of course, moving to typescript seems like the highest priority at this point, therefore I would recommend implementing this feature only after the rewrite.

Recommended project to support the new API - https://github.com/19majkel94/type-graphql.

**Comment by morbyosef** [comment]
Don't.
